version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8
    #    platform: linux/x86_64 #for m1 chip macs
    restart: always
    environment:
      MYSQL_DATABASE: ambassador_users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3366:3306"
